version: '3'
services:
  myapp:
    build: .
    image: topomodelx:new
    stdin_open: true
    tty: true
    volumes:
      - ${PWD}:/TopoModelX
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
   
